# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set Timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: 'Asia/Seoul'
        timezoneMacos: 'Asia/Seoul'
        timezoneWindows: 'Korea Standard Time'

    - name: Build
      run: |
         chmod +x ./build_with_flags.sh
         ./build_with_flags.sh -o egovchecker
      shell: bash

    - name: Test
      run: go test -v ./...
