name: Docker Build

on:
  push:
    tags: [ "v*" ]

jobs:

  build_docker_image:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: TAG="${{ github.ref#refs/tags/v }}" 
          
      - name: Docker build
        run: |
          docker build -t switchover/egovchecker .
          docker tag switchover/egovchecker switchover/egovchecker:$TAG

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: switchover
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker push
        run: |
          docker push switchover/egovchecker
          docker push switchover/egovchecker:$TAG
