name: Docker Build

on:
  push:
    tags: [ "v*" ]

jobs:

  build_docker_image:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker build
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build -t switchover/egovchecker .
          docker tag switchover/egovchecker switchover/egovchecker:${{ steps.tag.outputs.tag }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: switchover
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: |
          docker push switchover/egovchecker:${{ steps.tag.outputs.tag }}
          docker push switchover/egovchecker
